// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzMOx1nKH_P5VssVj_HrgtbuVqXmWOqtI',
    appId: '1:736864606063:web:4da5fdcf5145daa9bfba9a',
    messagingSenderId: '736864606063',
    projectId: 'flutter-test-f9ed4',
    authDomain: 'flutter-test-f9ed4.firebaseapp.com',
    databaseURL: 'https://flutter-test-f9ed4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-test-f9ed4.firebasestorage.app',
    measurementId: 'G-SSY3MQNXKB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_2ciq9w0EotqRHA21A1zmTH_K2DbV1eg',
    appId: '1:736864606063:android:96187070c09c776abfba9a',
    messagingSenderId: '736864606063',
    projectId: 'flutter-test-f9ed4',
    databaseURL: 'https://flutter-test-f9ed4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-test-f9ed4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDutGlgWvpvgUBau-KJWSG7YP1VZjHU_sI',
    appId: '1:736864606063:ios:738ffe5acbf3e692bfba9a',
    messagingSenderId: '736864606063',
    projectId: 'flutter-test-f9ed4',
    databaseURL: 'https://flutter-test-f9ed4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-test-f9ed4.firebasestorage.app',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDutGlgWvpvgUBau-KJWSG7YP1VZjHU_sI',
    appId: '1:736864606063:ios:738ffe5acbf3e692bfba9a',
    messagingSenderId: '736864606063',
    projectId: 'flutter-test-f9ed4',
    databaseURL: 'https://flutter-test-f9ed4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-test-f9ed4.firebasestorage.app',
    iosBundleId: 'com.example.flutterChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzMOx1nKH_P5VssVj_HrgtbuVqXmWOqtI',
    appId: '1:736864606063:web:aa0d73287b80b8bbbfba9a',
    messagingSenderId: '736864606063',
    projectId: 'flutter-test-f9ed4',
    authDomain: 'flutter-test-f9ed4.firebaseapp.com',
    databaseURL: 'https://flutter-test-f9ed4-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-test-f9ed4.firebasestorage.app',
    measurementId: 'G-V9E221W9WL',
  );
}
